"""Interactive app migration.

Revision ID: 2f3e822615d2
Revises: 
Create Date: 2025-02-05 15:20:17.611052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3e822615d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cost_factor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carrier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carrier_name'), ['name'], unique=True)

    op.create_table('shipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=128), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment')
    with op.batch_alter_table('carrier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carrier_name'))

    op.drop_table('carrier')
    # ### end Alembic commands ###
